alter table public.colab_bridge_access_keys
  drop constraint if exists colab_bridge_access_keys_key_kind_check;
alter table public.colab_bridge_access_keys
  add constraint colab_bridge_access_keys_key_kind_check
  check (key_kind in ('bridge', 'control', 'agent'));

create table public.colab_bridge_jobs (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in (
    'python', 'shell', 'pip', 'git', 'model_download', 'benchmark',
    'lora', 'export', 'file', 'drive_export', 'pipeline'
  )),
  spec jsonb not null check (jsonb_typeof(spec) = 'object'),
  project text not null default 'default'
    check (project ~ '^[A-Za-z0-9](?:[A-Za-z0-9_-]{0,62}[A-Za-z0-9])?$'),
  timeout_seconds integer not null default 900 check (timeout_seconds between 1 and 3600),
  runtime_id uuid references public.colab_bridge_runtimes(runtime_id) on delete set null,
  require_gpu boolean not null default false,
  idempotency_key text unique check (idempotency_key is null or length(idempotency_key) between 1 and 200),
  request_hash text not null check (request_hash ~ '^[0-9a-f]{64}$'),
  status text not null default 'queued'
    check (status in ('queued', 'running', 'cancelling', 'succeeded', 'failed', 'cancelled', 'timed_out', 'lost')),
  attempt integer not null default 1 check (attempt >= 1),
  parent_job_id uuid references public.colab_bridge_jobs(id) on delete restrict,
  lease_token uuid,
  lease_expires_at timestamptz,
  cancel_requested_at timestamptz,
  result jsonb,
  exit_code integer,
  error_code text check (error_code is null or error_code ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  check (
    (status in ('running', 'cancelling') and runtime_id is not null and lease_token is not null and lease_expires_at is not null)
    or
    (status not in ('running', 'cancelling') and lease_token is null and lease_expires_at is null)
  )
);

create index colab_bridge_jobs_queue_idx
  on public.colab_bridge_jobs (status, created_at)
  where status = 'queued';
create index colab_bridge_jobs_runtime_idx
  on public.colab_bridge_jobs (runtime_id, created_at desc);
create index colab_bridge_jobs_parent_idx
  on public.colab_bridge_jobs (parent_job_id)
  where parent_job_id is not null;
create unique index colab_bridge_jobs_one_active_runtime_idx
  on public.colab_bridge_jobs (runtime_id)
  where status in ('running', 'cancelling');

create table public.colab_bridge_job_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.colab_bridge_jobs(id) on delete cascade,
  runtime_id uuid not null references public.colab_bridge_runtimes(runtime_id) on delete restrict,
  attempt integer not null check (attempt >= 1),
  seq bigint not null check (seq >= 0),
  stream text not null check (stream in ('stdout', 'stderr', 'system')),
  text text not null check (length(text) <= 8192),
  created_at timestamptz not null default now(),
  unique (job_id, attempt, seq)
);

create index colab_bridge_job_events_cursor_idx
  on public.colab_bridge_job_events (job_id, seq);

create table public.colab_bridge_artifacts (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.colab_bridge_jobs(id) on delete cascade,
  runtime_id uuid not null references public.colab_bridge_runtimes(runtime_id) on delete restrict,
  attempt integer not null check (attempt >= 1),
  path text not null check (
    length(path) between 1 and 512
    and path !~ '(^/|\\\\|(^|/)\\.\\.?(/|$)|/$)'
  ),
  storage_path text not null unique,
  bytes bigint not null check (bytes >= 0),
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  mime_type text not null check (length(mime_type) between 1 and 200 and mime_type !~ '[\r\n]'),
  status text not null default 'prepared' check (status in ('prepared', 'published')),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  unique (job_id, attempt, path)
);

create index colab_bridge_artifacts_job_idx
  on public.colab_bridge_artifacts (job_id, created_at);

create table public.colab_bridge_lifecycle (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null unique default gen_random_uuid(),
  provider text not null check (provider in ('google_colab', 'external')),
  action text not null check (action in ('ensure', 'wake', 'release')),
  status text not null default 'accepted'
    check (status in ('accepted', 'starting', 'bootstrapping', 'ready', 'blocked', 'failed', 'released')),
  accelerator text,
  runtime_id uuid references public.colab_bridge_runtimes(runtime_id) on delete set null,
  request jsonb not null default '{}'::jsonb check (jsonb_typeof(request) = 'object'),
  error_code text check (error_code is null or error_code ~ '^[A-Z][A-Z0-9_]{0,63}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index colab_bridge_lifecycle_status_idx
  on public.colab_bridge_lifecycle (status, created_at desc);

alter table public.colab_bridge_jobs enable row level security;
alter table public.colab_bridge_job_events enable row level security;
alter table public.colab_bridge_artifacts enable row level security;
alter table public.colab_bridge_lifecycle enable row level security;

revoke all on public.colab_bridge_jobs from anon, authenticated;
revoke all on public.colab_bridge_job_events from anon, authenticated;
revoke all on public.colab_bridge_artifacts from anon, authenticated;
revoke all on public.colab_bridge_lifecycle from anon, authenticated;

create policy colab_bridge_jobs_deny_public on public.colab_bridge_jobs
  for all to anon, authenticated using (false) with check (false);
create policy colab_bridge_job_events_deny_public on public.colab_bridge_job_events
  for all to anon, authenticated using (false) with check (false);
create policy colab_bridge_artifacts_deny_public on public.colab_bridge_artifacts
  for all to anon, authenticated using (false) with check (false);
create policy colab_bridge_lifecycle_deny_public on public.colab_bridge_lifecycle
  for all to anon, authenticated using (false) with check (false);

grant all on public.colab_bridge_jobs to service_role;
grant all on public.colab_bridge_job_events to service_role;
grant all on public.colab_bridge_artifacts to service_role;
grant all on public.colab_bridge_lifecycle to service_role;
grant usage, select on sequence public.colab_bridge_job_events_id_seq to service_role;

create function public.colab_bridge_submit_job(
  p_kind text,
  p_spec jsonb,
  p_project text,
  p_timeout_seconds integer,
  p_runtime_id uuid,
  p_require_gpu boolean,
  p_idempotency_key text,
  p_request_hash text
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_job public.colab_bridge_jobs%rowtype;
begin
  if p_kind not in ('python', 'shell', 'pip', 'git', 'model_download', 'benchmark', 'lora', 'export', 'file', 'drive_export', 'pipeline')
    or jsonb_typeof(p_spec) is distinct from 'object'
    or p_project !~ '^[A-Za-z0-9](?:[A-Za-z0-9_-]{0,62}[A-Za-z0-9])?$'
    or p_timeout_seconds not between 1 and 3600
    or p_request_hash !~ '^[0-9a-f]{64}$'
    or (p_idempotency_key is not null and length(p_idempotency_key) not between 1 and 200)
  then
    return jsonb_build_object('ok', false, 'error_code', 'INVALID_JOB');
  end if;

  begin
    insert into public.colab_bridge_jobs (
      kind, spec, project, timeout_seconds, runtime_id, require_gpu,
      idempotency_key, request_hash
    ) values (
      p_kind, p_spec, p_project, p_timeout_seconds, p_runtime_id, p_require_gpu,
      p_idempotency_key, p_request_hash
    ) returning * into v_job;
  exception when unique_violation then
    if p_idempotency_key is null then raise; end if;
    select * into v_job from public.colab_bridge_jobs where idempotency_key = p_idempotency_key;
    if not found or v_job.request_hash <> p_request_hash then
      return jsonb_build_object('ok', false, 'error_code', 'IDEMPOTENCY_CONFLICT');
    end if;
    return jsonb_build_object('ok', true, 'job_id', v_job.id, 'status', v_job.status, 'idempotent', true);
  end;

  return jsonb_build_object('ok', true, 'job_id', v_job.id, 'status', v_job.status, 'idempotent', false);
end;
$$;

create function public.colab_bridge_list_jobs(
  p_status text,
  p_runtime_id uuid,
  p_limit integer
) returns jsonb
language sql
security invoker
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'ok', true,
    'jobs', coalesce(jsonb_agg(
      to_jsonb(q) - 'lease_token' - 'request_hash' - 'idempotency_key'
      order by q.created_at desc
    ), '[]'::jsonb)
  )
  from (
    select * from public.colab_bridge_jobs j
    where (p_status is null or j.status = p_status)
      and (p_runtime_id is null or j.runtime_id = p_runtime_id)
    order by j.created_at desc
    limit least(greatest(p_limit, 1), 100)
  ) q;
$$;

create function public.colab_bridge_get_job(p_job_id uuid) returns jsonb
language sql
security invoker
set search_path = public, pg_temp
as $$
  select coalesce(
    (select jsonb_build_object('ok', true, 'job', to_jsonb(j) - 'lease_token' - 'request_hash' - 'idempotency_key')
     from public.colab_bridge_jobs j where j.id = p_job_id),
    jsonb_build_object('ok', false, 'error_code', 'JOB_NOT_FOUND')
  );
$$;

create function public.colab_bridge_job_logs(
  p_job_id uuid,
  p_after bigint,
  p_limit integer
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_events jsonb;
begin
  if not exists (select 1 from public.colab_bridge_jobs where id = p_job_id) then
    return jsonb_build_object('ok', false, 'error_code', 'JOB_NOT_FOUND');
  end if;
  select coalesce(jsonb_agg(to_jsonb(e) order by e.seq), '[]'::jsonb)
    into v_events
  from (
    select id, job_id, attempt, seq, stream, text, created_at
    from public.colab_bridge_job_events
    where job_id = p_job_id and seq > p_after
    order by seq
    limit least(greatest(p_limit, 1), 1000)
  ) e;
  return jsonb_build_object('ok', true, 'events', v_events);
end;
$$;

create function public.colab_bridge_cancel_job(p_job_id uuid) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_job public.colab_bridge_jobs%rowtype;
begin
  select * into v_job from public.colab_bridge_jobs where id = p_job_id for update;
  if not found then return jsonb_build_object('ok', false, 'error_code', 'JOB_NOT_FOUND'); end if;
  if v_job.status = 'queued' then
    update public.colab_bridge_jobs
      set status = 'cancelled', cancel_requested_at = clock_timestamp(),
          completed_at = clock_timestamp(), updated_at = clock_timestamp()
      where id = p_job_id returning * into v_job;
  elsif v_job.status = 'running' then
    update public.colab_bridge_jobs
      set status = 'cancelling', cancel_requested_at = clock_timestamp(), updated_at = clock_timestamp()
      where id = p_job_id returning * into v_job;
  end if;
  return jsonb_build_object('ok', true, 'job_id', v_job.id, 'status', v_job.status);
end;
$$;

create function public.colab_bridge_retry_job(p_job_id uuid, p_idempotency_key text) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_source public.colab_bridge_jobs%rowtype;
  v_job public.colab_bridge_jobs%rowtype;
  v_hash text;
begin
  if length(p_idempotency_key) not between 1 and 200 then
    return jsonb_build_object('ok', false, 'error_code', 'INVALID_JOB');
  end if;
  select * into v_source from public.colab_bridge_jobs where id = p_job_id for update;
  if not found then return jsonb_build_object('ok', false, 'error_code', 'JOB_NOT_FOUND'); end if;
  if v_source.status not in ('succeeded', 'failed', 'cancelled', 'timed_out', 'lost') then
    return jsonb_build_object('ok', false, 'error_code', 'JOB_NOT_TERMINAL');
  end if;
  v_hash := encode(digest(v_source.id::text || ':' || p_idempotency_key, 'sha256'), 'hex');
  begin
    insert into public.colab_bridge_jobs (
      kind, spec, project, timeout_seconds, runtime_id, require_gpu,
      idempotency_key, request_hash, attempt, parent_job_id
    ) values (
      v_source.kind, v_source.spec, v_source.project, v_source.timeout_seconds,
      v_source.runtime_id, v_source.require_gpu, p_idempotency_key, v_hash,
      v_source.attempt + 1, v_source.id
    ) returning * into v_job;
  exception when unique_violation then
    select * into v_job from public.colab_bridge_jobs where idempotency_key = p_idempotency_key;
    if not found or v_job.parent_job_id is distinct from v_source.id then
      return jsonb_build_object('ok', false, 'error_code', 'IDEMPOTENCY_CONFLICT');
    end if;
    return jsonb_build_object('ok', true, 'job_id', v_job.id, 'status', v_job.status, 'idempotent', true);
  end;
  return jsonb_build_object('ok', true, 'job_id', v_job.id, 'status', v_job.status, 'idempotent', false);
end;
$$;

create function public.colab_bridge_claim_job(p_runtime_id uuid) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_runtime public.colab_bridge_runtimes%rowtype;
  v_job public.colab_bridge_jobs%rowtype;
  v_token uuid;
  v_restore jsonb;
  v_now timestamptz := clock_timestamp();
begin
  perform pg_advisory_xact_lock(hashtextextended(p_runtime_id::text, 0));
  select * into v_runtime from public.colab_bridge_runtimes
    where runtime_id = p_runtime_id for update;
  if not found then return jsonb_build_object('ok', false, 'error_code', 'NO_RUNTIME'); end if;

  update public.colab_bridge_jobs
    set status = case when status = 'cancelling' or cancel_requested_at is not null then 'cancelled' else 'lost' end,
        lease_token = null, lease_expires_at = null, completed_at = v_now, updated_at = v_now,
        error_code = case when status = 'cancelling' or cancel_requested_at is not null then null else 'LEASE_EXPIRED' end
    where status in ('running', 'cancelling')
      and lease_expires_at <= v_now;

  if v_runtime.runtime_metadata ->> 'execution_enabled' is distinct from 'true' then
    return jsonb_build_object('ok', true, 'job', null);
  end if;
  if exists (
    select 1 from public.colab_bridge_jobs
    where runtime_id = p_runtime_id and status in ('running', 'cancelling')
  ) then
    return jsonb_build_object('ok', true, 'job', null);
  end if;

  select j.* into v_job
  from public.colab_bridge_jobs j
  where status = 'queued'
    and (runtime_id is null or runtime_id = p_runtime_id)
    and (not require_gpu or v_runtime.accelerator in ('nvidia_gpu', 'nvidia'))
  order by created_at
  for update skip locked
  limit 1;
  if not found then return jsonb_build_object('ok', true, 'job', null); end if;

  v_token := gen_random_uuid();
  update public.colab_bridge_jobs
    set status = 'running', runtime_id = p_runtime_id, lease_token = v_token,
        lease_expires_at = v_now + interval '60 seconds',
        started_at = coalesce(started_at, v_now), updated_at = v_now
    where id = v_job.id
    returning * into v_job;

  if v_job.parent_job_id is not null then
    select coalesce(jsonb_agg(jsonb_build_object(
      'id', a.id, 'path', a.path, 'bytes', a.bytes, 'sha256', a.sha256, 'mime_type', a.mime_type
    ) order by a.created_at), '[]'::jsonb)
      into v_restore
    from public.colab_bridge_artifacts a
    where a.job_id = v_job.parent_job_id and a.status = 'published';
  end if;

  return jsonb_build_object('ok', true, 'job', jsonb_strip_nulls(jsonb_build_object(
    'id', v_job.id,
    'kind', v_job.kind,
    'spec', v_job.spec,
    'project', v_job.project,
    'timeout_seconds', v_job.timeout_seconds,
    'attempt', v_job.attempt,
    'lease_token', v_job.lease_token,
    'restore_artifacts', v_restore
  )));
end;
$$;

create function public.colab_bridge_heartbeat_job(
  p_runtime_id uuid,
  p_job_id uuid,
  p_lease_token uuid
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_job public.colab_bridge_jobs%rowtype;
  v_now timestamptz := clock_timestamp();
begin
  select * into v_job from public.colab_bridge_jobs where id = p_job_id for update;
  if not found or v_job.runtime_id is distinct from p_runtime_id or v_job.lease_token is distinct from p_lease_token
    or v_job.status not in ('running', 'cancelling') then
    return jsonb_build_object('ok', true, 'lease_valid', false, 'cancel_requested', false);
  end if;
  if v_job.lease_expires_at <= v_now then
    update public.colab_bridge_jobs
      set status = case when status = 'cancelling' or cancel_requested_at is not null then 'cancelled' else 'lost' end,
          lease_token = null, lease_expires_at = null, completed_at = v_now, updated_at = v_now,
          error_code = case when status = 'cancelling' or cancel_requested_at is not null then null else 'LEASE_EXPIRED' end
      where id = p_job_id and runtime_id = p_runtime_id and lease_token = p_lease_token;
    return jsonb_build_object('ok', true, 'lease_valid', false, 'cancel_requested', v_job.cancel_requested_at is not null);
  end if;
  update public.colab_bridge_jobs
    set lease_expires_at = v_now + interval '60 seconds', updated_at = v_now
    where id = p_job_id and runtime_id = p_runtime_id and lease_token = p_lease_token;
  return jsonb_build_object('ok', true, 'lease_valid', true, 'cancel_requested', v_job.status = 'cancelling' or v_job.cancel_requested_at is not null);
end;
$$;

create function public.colab_bridge_append_job_log(
  p_runtime_id uuid,
  p_job_id uuid,
  p_lease_token uuid,
  p_seq bigint,
  p_stream text,
  p_text text
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_job public.colab_bridge_jobs%rowtype;
begin
  select * into v_job from public.colab_bridge_jobs where id = p_job_id for update;
  if not found or v_job.runtime_id is distinct from p_runtime_id or v_job.lease_token is distinct from p_lease_token
    or v_job.status not in ('running', 'cancelling') or v_job.lease_expires_at <= clock_timestamp() then
    return jsonb_build_object('ok', false, 'error_code', 'LEASE_INVALID');
  end if;
  if p_seq < 0 or p_stream not in ('stdout', 'stderr', 'system') or length(p_text) > 8192 then
    return jsonb_build_object('ok', false, 'error_code', 'INVALID_PAYLOAD');
  end if;
  insert into public.colab_bridge_job_events (job_id, runtime_id, attempt, seq, stream, text)
    values (v_job.id, p_runtime_id, v_job.attempt, p_seq, p_stream, p_text)
    on conflict (job_id, attempt, seq) do nothing;
  return jsonb_build_object('ok', true);
end;
$$;

create function public.colab_bridge_complete_job(
  p_runtime_id uuid,
  p_job_id uuid,
  p_lease_token uuid,
  p_status text,
  p_result jsonb,
  p_exit_code integer,
  p_error_code text
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_job public.colab_bridge_jobs%rowtype;
begin
  if p_status not in ('succeeded', 'failed', 'cancelled', 'timed_out')
    or (p_error_code is not null and p_error_code !~ '^[A-Z][A-Z0-9_]{0,63}$') then
    return jsonb_build_object('ok', false, 'error_code', 'INVALID_PAYLOAD');
  end if;
  select * into v_job from public.colab_bridge_jobs where id = p_job_id for update;
  if not found or v_job.runtime_id is distinct from p_runtime_id or v_job.lease_token is distinct from p_lease_token
    or v_job.status not in ('running', 'cancelling') or v_job.lease_expires_at <= clock_timestamp() then
    return jsonb_build_object('ok', false, 'error_code', 'LEASE_INVALID');
  end if;
  update public.colab_bridge_jobs
    set status = p_status, result = p_result, exit_code = p_exit_code,
        error_code = p_error_code, lease_token = null, lease_expires_at = null,
        completed_at = clock_timestamp(), updated_at = clock_timestamp()
    where id = p_job_id and runtime_id = p_runtime_id and lease_token = p_lease_token;
  return jsonb_build_object('ok', true, 'job_id', p_job_id, 'status', p_status);
end;
$$;

create function public.colab_bridge_prepare_artifact(
  p_runtime_id uuid,
  p_job_id uuid,
  p_lease_token uuid,
  p_path text,
  p_bytes bigint,
  p_sha256 text,
  p_mime_type text
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_job public.colab_bridge_jobs%rowtype;
  v_artifact public.colab_bridge_artifacts%rowtype;
  v_id uuid := gen_random_uuid();
  v_storage_path text;
begin
  select * into v_job from public.colab_bridge_jobs where id = p_job_id for update;
  if not found or v_job.runtime_id is distinct from p_runtime_id or v_job.lease_token is distinct from p_lease_token
    or v_job.status not in ('running', 'cancelling') or v_job.lease_expires_at <= clock_timestamp() then
    return jsonb_build_object('ok', false, 'error_code', 'LEASE_INVALID');
  end if;
  if p_bytes < 0 or p_sha256 !~ '^[0-9a-f]{64}$' or length(p_mime_type) not between 1 and 200
    or length(p_path) not between 1 and 512 or p_path ~ '(^/|\\\\|(^|/)\\.\\.?(/|$)|/$)' then
    return jsonb_build_object('ok', false, 'error_code', 'INVALID_PAYLOAD');
  end if;
  select * into v_artifact from public.colab_bridge_artifacts
    where job_id = p_job_id and attempt = v_job.attempt and path = p_path;
  if found then
    if v_artifact.bytes = p_bytes and v_artifact.sha256 = p_sha256 and v_artifact.mime_type = p_mime_type
      and v_artifact.status = 'prepared' then
      return jsonb_build_object('ok', true, 'artifact_id', v_artifact.id, 'storage_path', v_artifact.storage_path);
    end if;
    return jsonb_build_object('ok', false, 'error_code', 'ARTIFACT_CONFLICT');
  end if;
  v_storage_path := p_runtime_id::text || '/' || p_job_id::text || '/' || v_job.attempt::text || '/' || v_id::text;
  insert into public.colab_bridge_artifacts (
    id, job_id, runtime_id, attempt, path, storage_path, bytes, sha256, mime_type
  ) values (
    v_id, p_job_id, p_runtime_id, v_job.attempt, p_path, v_storage_path, p_bytes, p_sha256, p_mime_type
  ) returning * into v_artifact;
  return jsonb_build_object('ok', true, 'artifact_id', v_artifact.id, 'storage_path', v_artifact.storage_path);
end;
$$;

create function public.colab_bridge_get_artifact(p_artifact_id uuid) returns jsonb
language sql
security invoker
set search_path = public, pg_temp
as $$
  select coalesce(
    (select jsonb_build_object('ok', true, 'artifact', to_jsonb(a))
     from public.colab_bridge_artifacts a where a.id = p_artifact_id),
    jsonb_build_object('ok', false, 'error_code', 'ARTIFACT_NOT_FOUND')
  );
$$;

create function public.colab_bridge_publish_artifact(
  p_runtime_id uuid,
  p_job_id uuid,
  p_lease_token uuid,
  p_artifact_id uuid
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_job public.colab_bridge_jobs%rowtype;
  v_artifact public.colab_bridge_artifacts%rowtype;
begin
  select * into v_job from public.colab_bridge_jobs where id = p_job_id for update;
  if not found or v_job.runtime_id is distinct from p_runtime_id or v_job.lease_token is distinct from p_lease_token
    or v_job.status not in ('running', 'cancelling') or v_job.lease_expires_at <= clock_timestamp() then
    return jsonb_build_object('ok', false, 'error_code', 'LEASE_INVALID');
  end if;
  select * into v_artifact from public.colab_bridge_artifacts
    where id = p_artifact_id and job_id = p_job_id and runtime_id = p_runtime_id and attempt = v_job.attempt
    for update;
  if not found then return jsonb_build_object('ok', false, 'error_code', 'ARTIFACT_NOT_FOUND'); end if;
  if v_artifact.status = 'prepared' then
    update public.colab_bridge_artifacts
      set status = 'published', published_at = clock_timestamp()
      where id = p_artifact_id;
  end if;
  return jsonb_build_object('ok', true, 'artifact_id', p_artifact_id);
end;
$$;

create function public.colab_bridge_list_artifacts(p_job_id uuid) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_artifacts jsonb;
begin
  if not exists (select 1 from public.colab_bridge_jobs where id = p_job_id) then
    return jsonb_build_object('ok', false, 'error_code', 'JOB_NOT_FOUND');
  end if;
  select coalesce(jsonb_agg(to_jsonb(a) - 'storage_path' order by a.created_at), '[]'::jsonb)
    into v_artifacts
  from public.colab_bridge_artifacts a
  where a.job_id = p_job_id and a.status = 'published';
  return jsonb_build_object('ok', true, 'artifacts', v_artifacts);
end;
$$;

revoke all on function public.colab_bridge_submit_job(text, jsonb, text, integer, uuid, boolean, text, text) from public;
revoke all on function public.colab_bridge_list_jobs(text, uuid, integer) from public;
revoke all on function public.colab_bridge_get_job(uuid) from public;
revoke all on function public.colab_bridge_job_logs(uuid, bigint, integer) from public;
revoke all on function public.colab_bridge_cancel_job(uuid) from public;
revoke all on function public.colab_bridge_retry_job(uuid, text) from public;
revoke all on function public.colab_bridge_claim_job(uuid) from public;
revoke all on function public.colab_bridge_heartbeat_job(uuid, uuid, uuid) from public;
revoke all on function public.colab_bridge_append_job_log(uuid, uuid, uuid, bigint, text, text) from public;
revoke all on function public.colab_bridge_complete_job(uuid, uuid, uuid, text, jsonb, integer, text) from public;
revoke all on function public.colab_bridge_prepare_artifact(uuid, uuid, uuid, text, bigint, text, text) from public;
revoke all on function public.colab_bridge_get_artifact(uuid) from public;
revoke all on function public.colab_bridge_publish_artifact(uuid, uuid, uuid, uuid) from public;
revoke all on function public.colab_bridge_list_artifacts(uuid) from public;

grant execute on function public.colab_bridge_submit_job(text, jsonb, text, integer, uuid, boolean, text, text) to service_role;
grant execute on function public.colab_bridge_list_jobs(text, uuid, integer) to service_role;
grant execute on function public.colab_bridge_get_job(uuid) to service_role;
grant execute on function public.colab_bridge_job_logs(uuid, bigint, integer) to service_role;
grant execute on function public.colab_bridge_cancel_job(uuid) to service_role;
grant execute on function public.colab_bridge_retry_job(uuid, text) to service_role;
grant execute on function public.colab_bridge_claim_job(uuid) to service_role;
grant execute on function public.colab_bridge_heartbeat_job(uuid, uuid, uuid) to service_role;
grant execute on function public.colab_bridge_append_job_log(uuid, uuid, uuid, bigint, text, text) to service_role;
grant execute on function public.colab_bridge_complete_job(uuid, uuid, uuid, text, jsonb, integer, text) to service_role;
grant execute on function public.colab_bridge_prepare_artifact(uuid, uuid, uuid, text, bigint, text, text) to service_role;
grant execute on function public.colab_bridge_get_artifact(uuid) to service_role;
grant execute on function public.colab_bridge_publish_artifact(uuid, uuid, uuid, uuid) to service_role;
grant execute on function public.colab_bridge_list_artifacts(uuid) to service_role;
