create extension if not exists pgcrypto;

create table if not exists public.colab_bridge_access_keys (
  key_kind text primary key check (key_kind in ('bridge', 'agent')),
  key_hash text not null check (key_hash ~ '^[0-9a-f]{64}$'),
  updated_at timestamptz not null default now()
);

create table if not exists public.colab_bridge_runtimes (
  runtime_id uuid primary key,
  label text not null default 'colab-runtime',
  accelerator text not null default 'unknown',
  runtime_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  last_heartbeat_at timestamptz not null default now()
);

create index if not exists colab_bridge_runtimes_heartbeat_idx
  on public.colab_bridge_runtimes (last_heartbeat_at desc);

create table if not exists public.colab_bridge_snapshots (
  id bigint generated by default as identity primary key,
  runtime_id uuid not null references public.colab_bridge_runtimes(runtime_id) on delete cascade,
  kind text not null check (kind in ('runtime', 'gpu', 'processes')),
  payload jsonb not null,
  observed_at timestamptz not null default now()
);

create index if not exists colab_bridge_snapshots_runtime_kind_idx
  on public.colab_bridge_snapshots (runtime_id, kind, observed_at desc);

create table if not exists public.colab_bridge_commands (
  id uuid primary key default gen_random_uuid(),
  runtime_id uuid not null references public.colab_bridge_runtimes(runtime_id) on delete cascade,
  command_type text not null check (command_type in ('refresh_gpu', 'refresh_runtime', 'refresh_processes')),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued' check (status in ('queued', 'claimed', 'completed', 'failed', 'rejected')),
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz
);

create index if not exists colab_bridge_commands_queue_idx
  on public.colab_bridge_commands (runtime_id, status, created_at);

create table if not exists public.colab_bridge_results (
  id bigint generated by default as identity primary key,
  command_id uuid not null unique references public.colab_bridge_commands(id) on delete cascade,
  runtime_id uuid not null references public.colab_bridge_runtimes(runtime_id) on delete cascade,
  status text not null check (status in ('completed', 'failed', 'rejected')),
  payload jsonb,
  error_code text,
  created_at timestamptz not null default now()
);

create index if not exists colab_bridge_results_runtime_idx
  on public.colab_bridge_results (runtime_id, created_at desc);

alter table public.colab_bridge_access_keys enable row level security;
alter table public.colab_bridge_runtimes enable row level security;
alter table public.colab_bridge_snapshots enable row level security;
alter table public.colab_bridge_commands enable row level security;
alter table public.colab_bridge_results enable row level security;

revoke all on public.colab_bridge_access_keys from anon, authenticated;
revoke all on public.colab_bridge_runtimes from anon, authenticated;
revoke all on public.colab_bridge_snapshots from anon, authenticated;
revoke all on public.colab_bridge_commands from anon, authenticated;
revoke all on public.colab_bridge_results from anon, authenticated;

create policy colab_bridge_access_keys_deny_public
  on public.colab_bridge_access_keys
  for all
  to anon, authenticated
  using (false)
  with check (false);

create policy colab_bridge_runtimes_deny_public
  on public.colab_bridge_runtimes
  for all
  to anon, authenticated
  using (false)
  with check (false);

create policy colab_bridge_snapshots_deny_public
  on public.colab_bridge_snapshots
  for all
  to anon, authenticated
  using (false)
  with check (false);

create policy colab_bridge_commands_deny_public
  on public.colab_bridge_commands
  for all
  to anon, authenticated
  using (false)
  with check (false);

create policy colab_bridge_results_deny_public
  on public.colab_bridge_results
  for all
  to anon, authenticated
  using (false)
  with check (false);
